### PR TITLE
use 512 px sized tiles by default

### PR DESCRIPTION
**Pull request by nvkelso**
(requires Tangram v0.13 or ES 0.8)

@bcamper I'm seeing a weird interaction between the raster hillshading and the vectors. It looks like the raster is showing 2x the detail using 512px tiles than the 256px tiles.

Either that's a Tangram bug or @rmarianski will need to have a look at how 512px terrain tiles are stitched. 

For the following view: 
> http://tangrams.github.io/walkabout-style/#9/38.3524/-120.8936

Prod using 256px:

screen shot 2017-09-11 at 16 52 44

Dev using 512px tiles (vector and raster) – is too detailed:

screen shot 2017-09-11 at 16 52 37

I suspect it's a Tangram thing as zoom 7 exhibits strange vector behavior, too:
> http://tangrams.github.io/walkabout-style/#7/38.352/-120.894

Prod using 256px:

screen shot 2017-09-11 at 16 54 29

Dev using 512px tiles (vector and raster) – is too detailed and some vectors gone like US-101 and I-5:

screen shot 2017-09-11 at 16 54 24

### CODE REVIEW

**Comment by nvkelso** [comment]
The same problem affects Tron (which also uses raster tiles in conjunction with vector tiles).

**Comment by bcamper** [comment]
It looks like this branch is still using the old tangram 0.12.x, which would explain that kind of behavior. Update to 0.13.x and try again?

**Comment by nvkelso** [comment]
Doh! I had checked Refill and a couple others in the set but failed here. Fixed in https://github.com/tangrams/walkabout-style/pull/193/commits/5c7265c0646308989692dcb5e32c835fd88c16b6.

**Comment by nvkelso** [comment]
Related:

- https://github.com/tangrams/walkabout-style-more-labels/pull/5
- https://github.com/tangrams/walkabout-style-no-labels/pull/2

**Pull request merged**
