### PR TITLE
Remove inapplicable 'base' draw parameter

### PR DESCRIPTION
**Pull request by matteblair**
'base' applies to styles, but not draw rules.

### CODE REVIEW

**Comment by nvkelso** [comment]
How does Tangram know that `highlight` is a line style then? Do we need to add `highlight` as a new **style** in the `styles` section?

**Comment by nvkelso** [comment]
I verified that the yellow highlights still draw using this branch, but am confused why that is. Leaving open until I get the 411 from @matteblair.

**Review by nvkelso — APPROVED** [review]

**Comment by matteblair** [comment]
`highlight` is declared as a style with `base: lines` in the main scene file: https://github.com/tangrams/walkabout-style/blob/gh-pages/walkabout-style.yaml#L875-L876

**Comment by matteblair** [comment]
Any more questions on this?

**Comment by nvkelso** [comment]
No questions, per say. For an include I’d rather have the styles not refer
to something in the base scene file so there aren’t gotchas, so I need to
think about that a bit.

**Comment by matteblair** [comment]
That's a good thought. 

But just to be clear, the lines removed here aren't extra, redundant specifiers of the style - they specify nothing at all. These wouldn't address the 'gotcha' that you're describing.

**Comment by matteblair** [comment]
Rebased against gh-pages. This still seems like a sensible clean-up.

**Comment by nvkelso** [comment]
Fixed in 190249aa6c109c2f7584ecc0b7c413847cb45243 instead.

**Pull request closed without merging**
