### PR TITLE
updated icons and more shields

### PR DESCRIPTION
**Pull request by sensescape**

### CODE REVIEW

**Comment by sensescape** [comment]
@bcamper working with @nvkelso , having some problems with shields, in Bubble Wrap and Refill, the same code correctly sizes the spritesheet with %, but in Cinnabar and Walkabout, they are oversized. Any ideas? 

Bubble Wrap's PR is here for comparison:
https://github.com/tangrams/bubble-wrap/pull/262

Looking at Dallas area, here:
http://localhost:7000/#13/32.8687/-96.8095

tangram-13-32 86870--96 80955-20180121719 1
tangram-13-32 86870--96 80955-20180121719
tangram-13-32 86870--96 80938-20180121719
tangram-13-32 86870--96 80940-20180121719

**Comment by bcamper** [comment]
Will take a look but I'll be traveling tomorrow so it might take a bit!

**Comment by bcamper** [comment]
Is the original issue here still a problem?

**Comment by nvkelso** [comment]
@bcamper yes, the weird extra large shields are still a problem in Walkabout (verified just now using latest commits in this branch).

**Comment by nvkelso** [comment]
To close the loop on this:

The generic shields that were TOO BIG were from oversized raster texture assets that didn't have size applied from default texture versus the shield textures with oversized raster texture sprites but with accommodating density applied. By resizing the shields to be sane, and setting density: 2 on them, and removing the size in the draw block, the problem is resolved and we reduce total lines of code.

**Pull request merged**
